navigation:
-   url: "/"
    title: "Home"
    image: "home.svg"
    color: "#36C9FF"
-   url: "/projects/"
    title: "Projects"
    image: "projects.svg"
    color: "#BF8040"
-   url: "/education/"
    title: "Education"
    image: "education.svg"
    color: "#FE8427"
-   url: "/contact/"
    title: "Contact"
    image: "contact.svg"
    color: "#9ACD32"
-   url: "http://www.github.com/benwoodworth"
    title: "GitHub"
    image: "github.svg"
    color: "#800080"
-   url: "http://www.linkedin.com/in/benjaminwoodworth"
    title: "LinkedIn"
    image: "linkedin.svg"
    color: "#0077B5"
